name: e2e

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  kubernetes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: engineerd/setup-kind@v0.5.0
      - name: Build container
        run: test/build.sh
      - name: Generate SSH key
        run: test/ssh-keygen.sh
      - name: Deploy and verify
        run: test/deploy.sh
      - name: Generate known_hosts
        run: test/ssh-keyscan.sh
      - name: Upload known_hosts
        uses: actions/upload-artifact@v1
        with:
          name: known_hosts
          path: known_hosts.txt
      - name: Test Git over SSH
        run: test/git-ls-remote.sh
      - name: Debug failure
        if: failure()
        run: test/debug.sh
  kubernetes-gpg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: engineerd/setup-kind@v0.5.0
      - name: Build container
        run: test/build.sh
      - name: Generate SSH key
        run: test/ssh-keygen.sh
      - name: Generate GPG key
        run: test/gpg-keygen.sh
      - name: Deploy and verify
        run: test/deploy.sh deploy-gpg
      - name: Generate known_hosts
        run: test/ssh-keyscan.sh
      - name: Test Git over SSH
        run: test/git-ls-remote.sh
      - name: Debug failure
        if: failure()
        run: test/debug.sh
